services:
  pec:
    container_name: pec
    platform: linux/amd64
    restart: unless-stopped
    volumes:
      - ./opt-esus:/opt/e-SUS
      - ./backups:/backups
    build:
      context: .
      dockerfile: Dockerfile.external-db
      args:
        - JAR_FILENAME=${JAR_FILENAME}
    stdin_open: true
    tty: true
    # Remova a seção ports: — não bind no host
    environment:
      # Vars de runtime limpas (sem duplicatas)
      - SERVICE_FQDN_PEC=${SERVICE_FQDN_PEC}
      - SERVICE_URL_PEC=${SERVICE_URL_PEC}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - ESUS_VERSION=${ESUS_VERSION}
      - HTTPS_DOMAIN=${HTTPS_DOMAIN}
      - INSTALL_TYPE=${INSTALL_TYPE}
      - POSTGRES_DB=${POSTGRES_DB}
      - TZ=${TZ}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # Labels para Traefik rotear (adicione isso para o proxy detectar)
    labels:
	- "traefik.enable=true"
	- "traefik.http.routers.pec.rule=Host(`esus.itagi.agilytech.com`)"
	- "traefik.http.routers.pec.entrypoints=websecure"
	- "traefik.http.services.pec.loadbalancer.server.port=8080"  # ← Confirme esta porta
	- "traefik.http.routers.pec.tls.certresolver=myresolver"
